
server:
  port: 8760

spring:
  application:
    name: spring-gateway
  rabbitmq:
    host: 182.92.217.197
    username: dev
    password: dev
    virtual-host: dev
    port: 5672
  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      httpclient:
        #全局连接超时设置默认45s(毫秒)
        connect-timeout: 45000
        response-timeout: 60s
      discovery:
        locator:
          #启用基于服务发现的路由定位
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 2  #流速 每秒
            redis-rate-limiter.burstCapacity: 10   #令牌桶的容积
            key-resolver: "#{@apiKeyResolver}" #SPEL表达式去的对应的bean
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/downtimeBack
  redis:
    port: 4307
    host: 182.92.217.197
    database: 0
    lettuce:
      pool:
        # 连接池最大连接数默认为8，负数代表不限制
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
    password: redis123456
eureka:
  instance:
    hostname: spring-gateway
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 5000