server:
  port: 8761
eureka:
  client:
    # 是否将自己注册到eureka服务器,默认false
    register-with-eureka: false
    # 客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: false
    #指示从eureka服务器获取注册表信息的频率（s）
    registry-fetch-interval-seconds: 30
    #更新实例信息的变化到Eureka服务端的间隔时间，（s）
    instance-info-replication-interval-seconds: 30
     #初始化实例信息到Eureka服务端的间隔时间，（s）
    initial-instance-info-replication-interval-seconds: 40
      #询问Eureka Server信息变化的时间间隔（s），默认为300秒
    eureka-service-url-poll-interval-seconds: 300
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  instance:
    #服务过期时间清理过期实例(s)
    lease-expiration-duration-in-seconds: 90
    # 定时调用renew接口维持心跳(s)
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: server-registry
