server:
  port: 8091

spring:
  application:
    name: webflux-demo
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://182.92.217.197:5432/faxin_test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
    pool-name: MyHikariCP
    minimum-idle: 10
    idle-timeout: 600000
    maximum-pool-size: 100
    max-lifetime: 1800000
    connection-timeout: 30000


eureka:
  instance:
    hostname: webflux-demo
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
       defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
