server:
  port: 8762

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          ##git 配置
          uri: file:///D:\work\cloud-config-demo
          username: 627898194@qq.com
          password: psw0719#xa
          default-label: master
          search-paths: config
          skip-ssl-validation: true
          #超时时间(s)
          timeout: 5
          #以秒为单位的刷新频率，0标识每次请求时从服务器获取
          refresh-rate: 0


eureka:
  instance:
    hostname: cloud-config-server
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
       defaultZone: http://192.168.3.68:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
